### ISSUE TITLE
Demos todo

### ISSUE THREAD

**Issue by Franky47** [Franky47/qml-intro#1]
List of things to try:
- [ ] Display an image with various pixel density (@1x, @2x, ...)
- [ ] Display a custom component using Canvas (knob)
- [ ] Interact with mouse & keyboard
